# Generates the RSA-2048 keypair that backs offline license verification
# (animus_verify_license, animus.hpp / animus_engine.cpp -- proprietary-edition
# branch only). Two halves, two very different lifecycles:
#
#   - The PUBLIC key gets baked into the shipped binary (every customer's
#     copy carries the same one) so animus_verify_license can check a
#     license file's signature without ever calling home. Written here as
#     a generated C++ header (animus_license_pubkey.hpp) meant to be
#     committed -- it's public by design, there's nothing to protect by
#     keeping it secret.
#   - The PRIVATE key signs license files and must never leave whoever
#     issues licenses. Written to license_tools/private/ (gitignored --
#     see .gitignore) specifically so it's never accidentally committed.
#     Anyone with this file can mint a license for any machine; treat it
#     like a root credential, not a build artifact.
#
# Uses .NET's RSACng directly (no OpenSSL, no external tooling) --
# GenericPublicBlob/GenericPrivateBlob export exactly the
# BCRYPT_RSAPUBLIC_BLOB/BCRYPT_RSAPRIVATE_BLOB wire format
# BCryptImportKeyPair expects on the verification side, confirmed by a
# real sign(PowerShell)/verify(BCryptVerifySignature) round trip before
# this script was relied on for anything.
$ErrorActionPreference = "Stop"

$privateDir = Join-Path $PSScriptRoot "private"
New-Item -ItemType Directory -Force -Path $privateDir | Out-Null

Write-Host "Generating RSA-2048 license-signing keypair..."
$rsa = [System.Security.Cryptography.RSACng]::new(2048)
$key = $rsa.Key
$publicBlob = $key.Export([System.Security.Cryptography.CngKeyBlobFormat]::GenericPublicBlob)
$privateBlob = $key.Export([System.Security.Cryptography.CngKeyBlobFormat]::GenericPrivateBlob)

$privateKeyPath = Join-Path $privateDir "license_private.blob"
[System.IO.File]::WriteAllBytes($privateKeyPath, $privateBlob)
Write-Host "Private key written to $privateKeyPath (KEEP THIS SECRET -- gitignored, never commit it)"

# Emit the public key as a C++ header -- see animus_engine.cpp's
# #include "animus_license_pubkey.hpp".
$headerPath = Join-Path (Join-Path $PSScriptRoot "..") "animus_license_pubkey.hpp"
$bytesPerLine = 16
$lines = New-Object System.Collections.Generic.List[string]
for ($i = 0; $i -lt $publicBlob.Length; $i += $bytesPerLine) {
    $chunk = $publicBlob[$i..([Math]::Min($i + $bytesPerLine - 1, $publicBlob.Length - 1))]
    $lines.Add("    " + (($chunk | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", ") + ",")
}
$headerContent = @"
#pragma once
// GENERATED by license_tools/generate_license_keypair.ps1 -- do not hand-edit.
// The public half of the RSA-2048 keypair animus_verify_license checks
// license signatures against (animus_engine.cpp). Safe to commit and ship:
// it's the public key, there's nothing here that grants signing authority.
// Regenerating this file invalidates every previously-issued license --
// see sign_license.ps1's own header for why that's usually not what you want.
namespace animus_license {
    static const unsigned char kPublicKeyBlob[] = {
$($lines -join "`n")
    };
    static const unsigned int kPublicKeyBlobSize = $($publicBlob.Length);
}
"@
[System.IO.File]::WriteAllText($headerPath, $headerContent, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Public key header written to $headerPath (safe to commit)"

$rsa.Dispose()
Write-Host ""
Write-Host "Done. Next: license_tools/sign_license.ps1 to issue a license file."
